apiVersion: apps/v1
kind: Deployment
metadata:
  name: william-deployment
  labels:
    app: archlab009-william
spec:
  replicas: 3
  selector:
    matchLabels:
      app: archlab009-william
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: archlab009-william
    spec:
      containers:
      - name: archlab009-william
        image: rivermaya/archlab009-william:1.0.0
        ports:
        - containerPort: 80
